### ISSUE TITLE
tooltip中formatter不支持回调函数

### ISSUE THREAD

**Issue by zhangjunling521** [yah0130/echarts-wx-uniapp#1]
目前需求使用uni-app开发，formatter字符串模板不能满足需求，要使用到回调函数的方式，但是代码不支持，麻烦问一下有没有实现支持回调函数的解决方案，谢谢
``tooltip: {
          trigger: "item",
          padding: [10, 10, 10, 10],
          backgroundColor: "#fff",
          extraCssText: "box-shadow:2px 2px 6px 0px rgba(0, 0, 0, 0.2);",
          textStyle: {
            color: "#FF84BB",
          },
          trigger: "item",
          // formatter: "{c0}",
		  formatter: (params) => {
			  console.log('>>>>>>>>>>', params);
		  }

**Comment by yah0130** [comment]
有的啊你可以拿到echart实例的调一下setoption就好了

**Comment by yah0130** [comment]
我更新了readme，你可以看下我写了个例子
