### ISSUE TITLE
我想问一下axisLabel.formatter为什么无效

### ISSUE THREAD

**Issue by thl1723298894** [yah0130/echarts-wx-uniapp#11]
axisLabel: {
							show: true,
							distance: -10,
							color: '#999',
							fontSize: 5,
							padding: [24, 0, 0, 0],
							formatter: function(value) {
								console.log('123', value)
								switch (value) {
									case 0:
										return 0; //首位刻度         
									case 100:
										return 200; //末尾刻度                         
									default:
										return '';
								}
							}
						},

上面代码中的formatter无法打印除’value‘ 想问一下怎么解决这个问题，而且其他配置中的formatter也一样无法打印出对应的参数

**Comment by yah0130** [comment]
> ```
> 					axisLabel: {
> 						show: true,
> 						distance: -10,
> 						color: '#999',
> 						fontSize: 5,
> 						padding: [24, 0, 0, 0],
> 						formatter: function(value) {
> 							console.log('123', value)
> 							switch (value) {
> 								case 0:
> 									return 0; //首位刻度         
> 								case 100:
> 									return 200; //末尾刻度                         
> 								default:
> 									return '';
> 							}
> 						}
> 					},
> ```
> 
> 上面代码中的formatter无法打印除’value‘ 想问一下怎么解决这个问题，而且其他配置中的formatter也一样无法打印出对应的参数

请参考我常见问题及解决方案中的第三点

**Comment by thl1723298894** [comment]
![image](https://user-images.githubusercontent.com/67083501/119331600-1c51e480-bcba-11eb-8637-0ec73427577c.png)
这没看到第三种吖
