### ISSUE TITLE
Y轴的文字axisLabel 下配置 formatter 不生效

### ISSUE THREAD

**Issue by frontend-qin** [yah0130/echarts-wx-uniapp#14]
yAxis: {
      type: 'value',
      splitLine: {
        lineStyle: {
          type: 'dashed'
        }
      `},`
      axisLabel: {
        formatter: function (value, index) {
          console.log(value, index);
          return value / 15 + "k" 
        }
      }
      // show: false
    }

**Comment by yah0130** [comment]
>  yAxis: {
>       type: 'value',
>       splitLine: {
>         lineStyle: {
>           type: 'dashed'
>         }
>       },
>       axisLabel: {
>         formatter: function (value, index) {
>           console.log(value, index);
>           return value / 15 + "k" 
>         }
>       }
>       // show: false
>     }

formatter函数序列化时会丢失请参考我的readme

**Comment by frontend-qin** [comment]
已参考解决
