### ISSUE TITLE
多图被悬浮无法滚动

### ISSUE THREAD

**Issue by wuufeii** [yah0130/echarts-wx-uniapp#6]
一个页面多张图表时被悬浮无法滚动；查看了一下，父级无absolut和fixed定位，只用了relative；请问是怎么回事，如何解决

**Comment by yah0130** [comment]
有代码或者截图吗

**Comment by wuufeii** [comment]
这样的








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yah0130/echarts-wx-uniapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 上午10:58
收件人:&nbsp;"yah0130/echarts-wx-uniapp"<echarts-wx-uniapp@noreply.github.com&gt;;
抄送:&nbsp;"邬飞"<wuufeii@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yah0130/echarts-wx-uniapp] 多图被悬浮无法滚动 (#6)





 
有代码或者截图吗

**Comment by yah0130** [comment]
？没看到东西啊

**Comment by wuufeii** [comment]
我邮箱回你

**Comment by wuufeii** [comment]
![image](https://user-images.githubusercontent.com/30976736/89486203-1ba49c00-d7d5-11ea-9290-a8f4ef51b349.png)

**Comment by wuufeii** [comment]
![image](https://user-images.githubusercontent.com/30976736/89486237-35de7a00-d7d5-11ea-9bce-c2c9328b6303.png)
![image](https://user-images.githubusercontent.com/30976736/89486261-4131a580-d7d5-11ea-80f3-002e20866ccb.png)
