### ISSUE TITLE
如何调用dispose销毁实例

### ISSUE THREAD

**Issue by zwl1233** [yah0130/echarts-wx-uniapp#7]

**Comment by zwl1233** [comment]
已解决,在微信小程序中,页面存在多个uni-ec-canvas, 来回切换6次以上  存在内存泄漏,导致微信崩溃,后在uni-ec-canvas.vue里加上啦dispose 就好啦
beforeDestroy(){
		this.$curChart.dispose()
	}

**Comment by yah0130** [comment]
> 已解决,在微信小程序中,页面存在多个uni-ec-canvas, 来回切换6次以上 存在内存泄漏,导致微信崩溃,后在uni-ec-canvas.vue里加上啦dispose 就好啦
> beforeDestroy(){
> this.$curChart.dispose()
> }

嗯对是这样调用的，最近有点忙
