### ISSUE TITLE
请问formatter回调函数如何使用

### ISSUE THREAD

**Issue by wuufeii** [yah0130/echarts-wx-uniapp#9]
我看之前你关闭的回答里说readme有例子，我没有看到呀

**Comment by yah0130** [comment]
> 我看之前你关闭的回答里说readme有例子，我没有看到呀

仔细看下常见问题那边

**Comment by wuufeii** [comment]
![image](https://user-images.githubusercontent.com/30976736/99508501-a2b20480-29bf-11eb-990b-e542ac7f5c14.png)
还有个问题，不是说可用压缩后的js代替吗，怎么又有提到“下载的文件放在 uni-ec-canvas/echarts.js，注意一定需要重命名为 echarts.js。”

**Comment by wuufeii** [comment]
请问怎么手动设置setOption；我看你那个例子有点没看到，那个参数怎么传；比如canvas传的是什么
